apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: jenkins-serviceaccount
type: kubernetes.io/service-account-token
