apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
rules:
  - apiGroups: ["apps"," ","batch"]
    resources: ["services","deployments","pods","secrets","statefulsets"]
    verbs: ["list","get","create","update"]
