# k8s/erp-app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-deployment
  labels:
    app: erp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-app
  template:
    metadata:
      labels:
        app: erp-app
    spec:
      containers:
      - name: erp-container
        # هذا هو المكان الذي سيتم تحديثه بواسطة Jenkins في المستقبل!
        image: ahmedsayedtalib/devops-gitops-demo:latest 
        ports:
        - containerPort: 8000 # منفذ تشغيل تطبيق Django
---
